export const TOGGLE_SIGNUP_FORM = 'TOGGLE_SIGNUP_FORM';
export const CHANGE_SIGNUP_FIELD = 'CHANGE_SIGNUP_FIELD';
export const ADD_SIGNUP_ERROR = 'ADD_SIGNUP_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CHANGE_LISTING_FIELD = 'CHANGE_LISTING_FIELD';
export const UPLOAD_LISTING_IMAGE = 'UPLOAD_LISTING_IMAGE';
